name: Test Semantic Release Tag Format

on:
  push:
    branches:
      - check-workflow
    paths:
      - "apps/user/**"

jobs:
  test-release:
    if: |
      !contains(github.event.head_commit.message, 'skip-ci')
    name: Test Semantic Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Yarn Clean Install
        run: yarn workspace user install

      - name: Install Semantic Release
        run: yarn global add semantic-release @semantic-release/{git,exec,changelog}

      - name: Test Default Tag Format
        run: semantic-release --dry-run --no-ci
        continue-on-error: true

      - name: Test Custom Tag Format
        run: semantic-release --dry-run --no-ci --tag-format 'user-v${version}'